// All user-facing copy for the Sequence-Method (Strategy & Tactics) tool, in
// both languages. The decision logic lives server-side in api/_sequence.js;
// this file only labels it. Hebrew is an idiomatic rendering using standard
// trading vocabulary. Technical tokens (MA5/MA20/MA40, CCI, Bollinger) stay in
// English on purpose — they are code identifiers.

export const CHECK_TITLES = {
  en: {
    M1: "Broad market not topping/falling (leading index)",
    S1: "Peaks AND troughs both rising (closing basis)",
    S2: "Volume rising or at least static",
    S3a: "MA20 above MA40",
    S3b: "MA40 sloping up — slope not flattening into decline",
    S3c: "MA20–MA40 gap widening or at least equal",
    S4: "Broken resistance now holding as support (closing basis)",
    G1: "MA5 stays above MA20 through the correction (5 > 20 > 40)",
    C1: "Falling sequence below MA5, MA5 sloping down",
    C2: "CCI(5) dropped ≤ −100 during the correction — and fresh",
    C3: "A candle entirely below the prior rise's highest-candle low",
    T1: "Falling sequence broke up — new trough above the prior peak",
    T2: "Reward / risk ratio ≥ 1.5 (hard gate)",
  },
  he: {
    M1: "השוק הרחב אינו בטופ/ירידה (מדד מוביל)",
    S1: "גם הפסגות וגם השפלים במבנה עולה (בסיס סגירה)",
    S2: "מחזורים עולים או לפחות סטטיים",
    S3a: "MA20 מעל MA40",
    S3b: "MA40 משופע מעלה — השיפוע אינו מתיישר לקראת ירידה",
    S3c: "המרווח בין MA20 ל-MA40 מתרחב או לפחות זהה",
    S4: "התנגדות שנפרצה מחזיקה כעת כתמיכה (בסיס סגירה)",
    G1: "MA5 נשאר מעל MA20 לאורך התיקון (5 > 20 > 40)",
    C1: "הרצף היורד מתחת ל-MA5, ו-MA5 משופע כלפי מטה",
    C2: "ה-CCI(5) ירד ל-100- ומטה במהלך התיקון — וטרי",
    C3: "נר אחד לפחות כולו מתחת לנמוך של נר השיא ברצף הקודם",
    T1: "הרצף היורד נשבר כלפי מעלה — שפל חדש מעל השיא הקודם",
    T2: "יחס סיכוי/סיכון ≥ 1.5 (שער קשיח)",
  },
};

export const T = {
  en: {
    dir: "ltr",
    modeAnalyzer: "9-Question",
    modeStrategy: "Strategy & Tactics",
    appTitle: "Strategy & Tactics",
    appSub: "THE SEQUENCE METHOD",
    market: { US: "US", TLV: "TLV" },
    techniqueLabel: "Technique",
    tech1: "Cascade",
    tech2: "Single TF",
    tech1Full: "Technique 1 — Cascade (monthly → weekly → daily)",
    tech2Full: "Technique 2 — Single timeframe + MA5 gate",
    techHelp:
      "Choose ONE tactic. Technique 1 walks monthly → weekly → daily and the level where a falling sequence appears sets the trade horizon (very few mistakes, more effort). Technique 2 trades a single timeframe you pick and adds the MA5 > MA20 entry gate to compensate for dropping multi-timeframe confirmation.",
    timeframe: "Timeframe",
    symbolPlaceholder: "SYMB",
    analyze: "Analyze",
    swing: "Swing sensitivity",
    swingHelp:
      "How many candles on each side of a bar must be lower (peak) or higher (trough) before it counts as a real swing point — on a closing basis. Higher = stricter, fewer/larger swings. Drives S1, S4, the correction/break detection and the target.",
    emptyList: "Analyze a stock to add it to your list",
    sort: {
      button: "Sorting",
      title: "Sort the scan list",
      az: { label: "A–Z", hint: "by name" },
      buy: { label: "Buy", hint: "buy at top" },
      market: { label: "Market", hint: "US at top" },
      dm: { label: "D–M", hint: "daily → monthly" },
    },
    selectPrompt: "Select a stock to view the strategy analysis",
    analyzing: (t) => `Analyzing ${t}…`,
    failed: (t, e) => `Couldn't analyze ${t} — ${e}`,
    failedShort: "Failed to analyze",
    fetched: "Fetched",
    refresh: "Refresh",
    backToList: "‹ Stock list",
    batch: {
      button: "Batch analysis",
      buttonTitle: "Upload a CSV to scan many stocks at once",
      demo: "Demo file",
      demoTitle: "Download an example CSV file",
      title: "Batch analysis scan",
      foundParts: (n) => ({ mid: ` stock${n === 1 ? "" : "s"} ${n === 1 ? "was" : "were"} found in `, post: ". Uploading it will initiate the scan of all of them." }),
      cancel: "Cancel",
      scanAll: "Scan all",
    },
    groups: {
      market: { title: "Market", caption: "ASSESS FIRST" },
      strategy: { title: "Strategy — should we buy?", caption: "STEP 1 · ALL MUST PASS" },
      tactic: { title: "Tactic — how to enter", caption: "STEP 2" },
      correction: { title: "Correction check", caption: "STEP 3" },
      timing: { title: "Timing check", caption: "STEP 4" },
    },
    verdict: {
      BUY: "Buy", BUY_LIMIT: "Buy — limit", DO_NOT_ENTER: "Do not enter",
      NO_TRADE: "No trade", MARKET_VOID: "Market void", INCOMPLETE: "Incomplete",
    },
    horizonLabel: "Horizon",
    horizon: { long: "Long-term", medium: "Medium-term", short: "Short-term", none: "No valid setup" },
    horizonOn: (tf) => `traded on ${tf}`,
    cascadeReason: {
      "falling-sequence": (tf) => `Falling sequence appeared on the ${tf} → horizon set there.`,
      "daily-break-search": () => "No falling sequence on monthly/weekly → drop to the daily and trade the break (short-term).",
      "no-setup": () => "No valid setup on any timeframe → no trade.",
      single: (tf) => `Single timeframe (${tf}); MA5 > MA20 entry gate applies.`,
    },
    risk: "Risk", reward: "Reward", ratio: "Ratio",
    math: { title: "The Math", caption: "RISK / REWARD" },
    buy: "Buy (last close)", buySub: "Last close price",
    stop: "Stop (breaking-candle low)", stopSub: "Low incl. tail of the candle that broke the sequence",
    target: "Target (prior peak)", targetSub: "Up to the prior peak is yours; beyond is bonus",
    ratioLow: (mb, cur) => `Ratio below 1.5 → hard gate fails. Max valid limit-buy (ratio = 1.5): `,
    ratioLowTail: "Or wait for a deeper pullback / better break.",
    buyTiming: { title: "Buy timing (long-term)", caption: "THREE OPTIONS" },
    optA: "A · Limit at mid-candle",
    optASub: (cur) => `[(high+low)/2], valid one month, at a price giving ≥ 1.5 : 1`,
    optB: "B · Drop to daily",
    optBSub: "Buy the next falling-sequence break (act now)",
    optC: "C · Half and half",
    optCSub: "Split between A and B",
    noPrePost: "Avoid pre-market / after-market for these entries (unreliable fills).",
    position: { title: "Position management", caption: "AFTER ENTRY" },
    riskZeroYes: "Risk-zero trigger ACTIVE: latest candle is green and entirely above a rising MA5 → risk ≈ 0. This is the cue to add the next position.",
    riskZeroNo: "Risk-zero trigger not yet active: wait for a green candle entirely above a rising MA5 before adding the next position. Only add after the previous position has cleared the risk zone.",
    sell: { title: "Sell signals", caption: "ANY ONE TRIGGERS AN EXIT" },
    sellItems: (m, cur, lastIsSeller) => [
      ["Break of the rising sequence", `Close below ${fmtv(m.risingSeqLow)} ${cur} (low of the rising sequence's highest candle) ⇒ sell, no discretion.`],
      ["Red candle above the upper Bollinger band", `Upper band ≈ ${fmtv(m.upperBand)} ${cur}. An up-move ending red above it ⇒ weakness.`],
      ["Seller candle after a rise, above the band", lastIsSeller ? "The latest candle already shows this (small body, upper tail ≥ 2× body)." : "Small body low, upper tail ≥ 2× body = sellers regaining control."],
    ],
    chart: { title: "Chart", caption: "GENERATED FROM THE DATA" },
    chartHint: "Scroll to zoom · Shift-scroll or drag to pan",
    expand: "⤢ Expand", close: "Close",
    tiers: ["Minimal", "Core", "Full"],
    legend: { ma5: "MA5", ma20: "MA20", ma40: "MA40", levels: "Buy / Stop / Target", pivots: "Swing pivots (close)", boll: "Bollinger (10/1)" },
    edited: "EDITED",
    confTip: { exact: "Deterministic formula from the data", swing: "Deterministic given your swing setting — check the pivots", guess: "Best-effort interpretation — confirm visually" },
    notAdvice: "A faithful implementation of the Sequence Method. Not investment advice.",
  },
  he: {
    dir: "rtl",
    modeAnalyzer: "9 שאלות",
    modeStrategy: "אסטרטגיה וטקטיקות",
    appTitle: "אסטרטגיה וטקטיקות",
    appSub: "שיטת הרצפים",
    market: { US: "ארה״ב", TLV: "ת״א" },
    techniqueLabel: "טכניקה",
    tech1: "מפל",
    tech2: "מימד בודד",
    tech1Full: "טכניקה 1 — מפל מימדי זמן (חודשי → שבועי → יומי)",
    tech2Full: "טכניקה 2 — מימד זמן בודד + שער MA5",
    techHelp:
      "בוחרים טקטיקה אחת. טכניקה 1 יורדת חודשי → שבועי → יומי, והמימד שבו מופיע רצף יורד קובע את טווח העסקה (מעט טעויות, יותר מאמץ). טכניקה 2 סוחרת מימד זמן אחד שבחרתם ומוסיפה את שער הכניסה MA5 > MA20 כפיצוי על הוויתור על אישור רב-מימדי.",
    timeframe: "מימד זמן",
    symbolPlaceholder: "סמל",
    analyze: "נתח",
    swing: "רגישות תנודה",
    swingHelp:
      "כמה נרות בכל צד של נר חייבים להיות נמוכים יותר (פסגה) או גבוהים יותר (שפל) כדי שייחשב נקודת מפנה — על בסיס סגירה. גבוה יותר = מחמיר יותר, פחות תנודות וגדולות יותר. משפיע על S1, S4, זיהוי התיקון/השבירה והיעד.",
    emptyList: "נתחו מנייה כדי להוסיף אותה לרשימה",
    sort: {
      button: "מיון",
      title: "מיון רשימת הסריקות",
      az: { label: "א–ת", hint: "לפי שם" },
      buy: { label: "קנייה", hint: "קנייה למעלה" },
      market: { label: "שוק", hint: "ארה״ב למעלה" },
      dm: { label: "יומי–חודשי", hint: "יומי → חודשי" },
    },
    selectPrompt: "בחרו מנייה כדי לראות את ניתוח האסטרטגיה",
    analyzing: (t) => `מנתח את ${t}…`,
    failed: (t, e) => `לא ניתן לנתח את ${t} — ${e}`,
    failedShort: "הניתוח נכשל",
    fetched: "נמשך",
    refresh: "רענון",
    backToList: "‹ רשימת מניות",
    batch: {
      button: "ניתוח מרובה",
      buttonTitle: "העלו קובץ CSV לסריקת מספר מניות בבת אחת",
      demo: "קובץ דמו",
      demoTitle: "הורידו קובץ CSV לדוגמה",
      title: "סריקת ניתוח מרובה",
      foundParts: (n) => ({ mid: ` מניות נמצאו בקובץ `, post: ". העלאתו תתחיל בסריקה של כולן." }),
      cancel: "ביטול",
      scanAll: "סרוק הכול",
    },
    groups: {
      market: { title: "שוק", caption: "בדיקה ראשונה" },
      strategy: { title: "אסטרטגיה — האם לקנות?", caption: "שלב 1 · הכול חייב לעבור" },
      tactic: { title: "טקטיקה — איך נכנסים", caption: "שלב 2" },
      correction: { title: "בדיקת התיקון", caption: "שלב 3" },
      timing: { title: "בדיקת התזמון", caption: "שלב 4" },
    },
    verdict: {
      BUY: "קנייה", BUY_LIMIT: "קנייה — limit", DO_NOT_ENTER: "אין כניסה",
      NO_TRADE: "אין עסקה", MARKET_VOID: "השוק חוסם", INCOMPLETE: "חסר מידע",
    },
    horizonLabel: "טווח",
    horizon: { long: "טווח ארוך", medium: "טווח בינוני", short: "טווח קצר", none: "אין setup תקף" },
    horizonOn: (tf) => `נסחר ב${tf}`,
    cascadeReason: {
      "falling-sequence": (tf) => `רצף יורד הופיע ב${tf} → הטווח נקבע שם.`,
      "daily-break-search": () => "אין רצף יורד בחודשי/שבועי → יורדים ליומי וסוחרים את השבירה (טווח קצר).",
      "no-setup": () => "אין setup תקף באף מימד → אין עסקה.",
      single: (tf) => `מימד זמן בודד (${tf}); חל שער הכניסה MA5 > MA20.`,
    },
    risk: "סיכון", reward: "סיכוי", ratio: "יחס",
    math: { title: "החישוב", caption: "סיכון / סיכוי" },
    buy: "קנייה (סגירה אחרונה)", buySub: "מחיר הסגירה האחרון",
    stop: "סטופ (נמוך נר השבירה)", stopSub: "הנמוך (כולל צל) של הנר ששבר את הרצף",
    target: "יעד (השיא הקודם)", targetSub: "עד השיא הקודם זה שלך; מעבר זה בונוס",
    ratioLow: (mb, cur) => `היחס מתחת ל-1.5 → השער הקשיח נכשל. מחיר limit מקסימלי תקף (יחס = 1.5): `,
    ratioLowTail: "או להמתין לתיקון עמוק יותר / שבירה טובה יותר.",
    buyTiming: { title: "תזמון קנייה (טווח ארוך)", caption: "שלוש אפשרויות" },
    optA: "א · limit לאמצע הנר",
    optASub: (cur) => `[(גבוה+נמוך)/2], בתוקף לחודש, במחיר שנותן יחס ≥ 1.5 : 1`,
    optB: "ב · לרדת ליומי",
    optBSub: "לקנות את שבירת הרצף היורד הבאה (פעולה מיידית)",
    optC: "ג · חצי וחצי",
    optCSub: "פיצול בין א׳ ל-ב׳",
    noPrePost: "להימנע מפרה-מרקט / אפטר-מרקט בכניסות אלה (מילוי לא אמין).",
    position: { title: "ניהול פוזיציה", caption: "אחרי כניסה" },
    riskZeroYes: "טריגר סיכון-אפס פעיל: הנר האחרון ירוק וכולו מעל MA5 משופע מעלה → סיכון ≈ 0. זהו הסימן להוסיף את הפוזיציה הבאה.",
    riskZeroNo: "טריגר סיכון-אפס אינו פעיל עדיין: המתינו לנר ירוק כולו מעל MA5 משופע מעלה לפני הוספת פוזיציה. מוסיפים רק אחרי שהקודמת יצאה מאזור הסיכון.",
    sell: { title: "איתותי מכירה", caption: "כל אחד מהם מפעיל יציאה" },
    sellItems: (m, cur, lastIsSeller) => [
      ["שבירת הרצף העולה", `סגירה מתחת ל-${fmtv(m.risingSeqLow)} ${cur} (הנמוך של נר השיא ברצף העולה) ⇐ מוכרים, בלי שיקול דעת.`],
      ["נר אדום מעל רצועת Bollinger העליונה", `הרצועה העליונה ≈ ${fmtv(m.upperBand)} ${cur}. עלייה שמסתיימת באדום מעליה ⇐ חולשה.`],
      ["נר מוכרים אחרי עלייה, מעל הרצועה", lastIsSeller ? "הנר האחרון כבר מציג זאת (גוף קטן, צל עליון ≥ פי 2 מהגוף)." : "גוף קטן למטה, צל עליון ≥ פי 2 מהגוף = המוכרים חוזרים לשלוט."],
    ],
    chart: { title: "גרף", caption: "נוצר מהנתונים" },
    chartHint: "גלילה לזום · Shift-גלילה או גרירה להזזה",
    expand: "⤢ הגדלה", close: "סגירה",
    tiers: ["מינימלי", "ליבה", "מלא"],
    legend: { ma5: "MA5", ma20: "MA20", ma40: "MA40", levels: "קנייה / סטופ / יעד", pivots: "נקודות תנודה (סגירה)", boll: "Bollinger (10/1)" },
    edited: "נערך",
    confTip: { exact: "נוסחה דטרמיניסטית מהנתונים", swing: "דטרמיניסטי לפי הגדרת התנודה — בדקו את הנקודות", guess: "פרשנות מיטבית — ודאו ויזואלית" },
    notAdvice: "מימוש נאמן של שיטת הרצפים. אינו ייעוץ השקעות.",
  },
};

function fmtv(x) { return x == null || isNaN(x) ? "—" : Number(x).toFixed(2); }
