// All user-facing copy for the Advanced Chart mode. Follows the same pattern
// as src/strategy/strings.js: logic lives server-side (api/chart.js +
// api/_peaks.js); this file only labels it. Technical tokens (RSI, MACD, SMA,
// EMA, Bollinger, HH/HL/LH/LL) stay in English on purpose — they are chart
// vocabulary.

export const CT = {
  en: {
    dir: "ltr",
    appTitle: "Advanced Chart",
    appSub: "TECHNICAL ANALYSIS · PEAKS & TROUGHS",
    market: { US: "US", TLV: "TLV" },
    symbolPlaceholder: "SYMB",
    symbolPlaceholderTLV: "TEVA · 629014 · טבע",
    load: "Load",
    loading: "Loading…",
    failed: (t, e) => `Couldn't load ${t} — ${e}`,
    emptyPrompt: "Enter a symbol to load its chart",
    ranges: ["1M", "3M", "6M", "1Y", "2Y", "5Y", "Max"],
    interval: { "1d": "Daily", "1wk": "Weekly", "1mo": "Monthly" },
    chartHint: "Scroll to zoom · Shift-scroll or drag to pan",
    lastClose: "Last close",
    indicators: "Indicators",
    panels: "Panels",
    overlays: "Overlays",
    structure: "Structure",
    sensitivity: "Swing sensitivity",
    sensitivityHelp: "Higher = only the larger swings count as peaks/troughs. Drives the zigzag, the HH/HL/LH/LL labels, support/resistance and the Fibonacci leg.",
    zigzagMode: { percent: "% reversal", lookback: "Bar lookback" },
    trend: { uptrend: "Uptrend", downtrend: "Downtrend", range: "Range" },
    trendWhy: "Why?",
    srKind: { support: "Support", resistance: "Resistance", flip: "Flip zone" },
    touches: (n) => `${n} touches`,
    legend: {
      zigzag: "Zigzag (peaks & troughs)",
      sr: "Support / Resistance",
      fib: "Fibonacci",
      boll: "Bollinger (20/2)",
      lastPrice: "Last price",
    },
    notAdvice: "Charts generated from public market data. Not investment advice.",
  },
  he: {
    dir: "rtl",
    appTitle: "גרף מתקדם",
    appSub: "ניתוח טכני · פסגות ושפלים",
    market: { US: "ארה״ב", TLV: "ת״א" },
    symbolPlaceholder: "סמל",
    symbolPlaceholderTLV: "סמל · מס' נייר · שם",
    load: "טען",
    loading: "טוען…",
    failed: (t, e) => `לא ניתן לטעון את ${t} — ${e}`,
    emptyPrompt: "הזינו סמל כדי לטעון את הגרף",
    ranges: ["1M", "3M", "6M", "1Y", "2Y", "5Y", "Max"],
    interval: { "1d": "יומי", "1wk": "שבועי", "1mo": "חודשי" },
    chartHint: "גלילה לזום · Shift-גלילה או גרירה להזזה",
    lastClose: "סגירה אחרונה",
    indicators: "אינדיקטורים",
    panels: "פאנלים",
    overlays: "שכבות",
    structure: "מבנה",
    sensitivity: "רגישות תנודה",
    sensitivityHelp: "גבוה יותר = רק התנודות הגדולות נחשבות פסגות/שפלים. משפיע על הזיגזג, תוויות HH/HL/LH/LL, תמיכה/התנגדות ורגל הפיבונאצ'י.",
    zigzagMode: { percent: "היפוך %", lookback: "נרות סביב" },
    trend: { uptrend: "מגמה עולה", downtrend: "מגמה יורדת", range: "דשדוש" },
    trendWhy: "למה?",
    srKind: { support: "תמיכה", resistance: "התנגדות", flip: "אזור היפוך" },
    touches: (n) => `${n} נגיעות`,
    legend: {
      zigzag: "זיגזג (פסגות ושפלים)",
      sr: "תמיכה / התנגדות",
      fib: "פיבונאצ'י",
      boll: "Bollinger (20/2)",
      lastPrice: "מחיר אחרון",
    },
    notAdvice: "הגרפים נוצרים מנתוני שוק ציבוריים. אינו ייעוץ השקעות.",
  },
};
