// All user-facing copy for the Monthly Tracker tool, in both languages. The
// decision logic lives server-side in api/_tracker.js; this file only labels
// it. Hebrew keeps the method's original wording. MA5 stays in English on
// purpose — it is a code identifier.

export const CHECK_TITLES = {
  en: {
    N1: "Tradable — avg daily volume above 1,000,000 (lenient 800,000)",
    N2: "Rising sequence (monthly chart)",
    N3: "Whole candle above MA5 — including the lower tail",
    N4: "MA5 sloping upward",
    N5: "Last closed candle is green",
    N6: "Close above the previous candle's high",
    N7: "Close in the top third of its own candle (near its high)",
  },
  he: {
    N1: "הנייר סחיר — מחזור מסחר יומי ממוצע מעל 1,000,000 (או 800,000)",
    N2: "רצף עולה (גרף חודשי)",
    N3: "כל הנר, כולל הצל התחתון, מעל ממוצע נע 5",
    N4: "הממוצע הנע (5) משופע כלפי מעלה",
    N5: "הנר האחרון שנסגר ירוק",
    N6: "שער הסגירה גבוה מהגבוה של הנר הקודם",
    N7: "הסגירה בשליש העליון של הנר — סמוך לגבוה של עצמו",
  },
};

export const T = {
  en: {
    dir: "ltr",
    market: { US: "US", TLV: "TLV" },
    symbolPlaceholder: "SYMB",
    symbolPlaceholderTLV: "TEVA · 629014 · טבע",
    analyze: "Scan",
    emptyList: "Scan a stock to see if it belongs on this month's tracking list",
    selectPrompt: "Select a stock to view the monthly tracking checks",
    analyzing: (t) => `Scanning ${t}…`,
    failed: (t, e) => `Couldn't scan ${t} — ${e}`,
    failedShort: "Failed to scan",
    fetched: "Fetched",
    refresh: "Refresh",
    backToList: "‹ Stock list",
    monthly: "Monthly",
    evalOn: (d) => `last closed candle: ${d}`,
    formingNote: "The current month's candle is still forming — it appears on the chart but is excluded from the checks.",
    avgVolume: "Avg daily volume",
    batch: {
      button: "Batch scan",
      buttonTitle: "Upload a CSV to scan many stocks at once",
      demo: "Demo file",
      demoTitle: "Download an example CSV file",
      title: "Batch tracking scan",
      foundParts: (n) => ({ mid: ` stock${n === 1 ? "" : "s"} ${n === 1 ? "was" : "were"} found in `, post: ". Uploading it will initiate the scan of all of them." }),
      cancel: "Cancel",
      scanAll: "Scan all",
    },
    groups: {
      liquidity: { title: "Liquidity", caption: "GATE · TRADABLE PAPER ONLY" },
      trend: { title: "Monthly trend", caption: "STRUCTURE · ALL MUST PASS" },
      alert: { title: "Buy-alert candle", caption: "THE LAST CLOSED CANDLE" },
    },
    verdict: {
      TRACK: "Add to tracking",
      WAIT: "Trend OK — no alert candle",
      NO_TRACK: "Not for tracking",
      INCOMPLETE: "Incomplete",
    },
    verdictHint: {
      TRACK: "All seven checks pass — the stock goes on this month's tracking list and the last candle is a buy alert.",
      WAIT: "Liquidity and the monthly trend pass, but the last closed candle isn't an alert candle yet. Re-check next month.",
      NO_TRACK: "The liquidity gate or the monthly trend failed — leave it off the list.",
      INCOMPLETE: "Some checks could not be answered from the data — fill them in manually.",
    },
    chart: { title: "Chart", caption: "MONTHLY CANDLES + MA5" },
    chartHint: "Scroll or pinch to zoom · Shift-scroll or drag to pan · Tap for crosshair",
    legendMa5: "MA5",
    edited: "EDITED",
    confTip: { exact: "Deterministic formula from the data", swing: "Deterministic given the swing setting — check the pivots", guess: "Best-effort interpretation — confirm visually" },
  },
  he: {
    dir: "rtl",
    market: { US: "ארה״ב", TLV: "ת״א" },
    symbolPlaceholder: "סמל",
    symbolPlaceholderTLV: "סמל · מס' נייר · שם",
    analyze: "סרוק",
    emptyList: "סרקו מנייה כדי לבדוק אם היא שייכת לרשימת המעקב של החודש",
    selectPrompt: "בחרו מנייה כדי לראות את בדיקות המעקב החודשי",
    analyzing: (t) => `סורק את ${t}…`,
    failed: (t, e) => `לא ניתן לסרוק את ${t} — ${e}`,
    failedShort: "הסריקה נכשלה",
    fetched: "נמשך",
    refresh: "רענון",
    backToList: "‹ רשימת מניות",
    monthly: "חודשי",
    evalOn: (d) => `הנר הסגור האחרון: ${d}`,
    formingNote: "נר החודש הנוכחי עדיין נבנה — הוא מוצג בגרף אך אינו נכלל בבדיקות.",
    avgVolume: "מחזור יומי ממוצע",
    batch: {
      button: "סריקה מרובה",
      buttonTitle: "העלו קובץ CSV לסריקת מספר מניות בבת אחת",
      demo: "קובץ דמו",
      demoTitle: "הורידו קובץ CSV לדוגמה",
      title: "סריקת מעקב מרובה",
      foundParts: (n) => ({ mid: ` מניות נמצאו בקובץ `, post: ". העלאתו תתחיל בסריקה של כולן." }),
      cancel: "ביטול",
      scanAll: "סרוק הכול",
    },
    groups: {
      liquidity: { title: "סחירות", caption: "שער כניסה · רק נייר סחיר" },
      trend: { title: "מגמה חודשית", caption: "מבנה · הכול חייב לעבור" },
      alert: { title: "נר איתות קנייה", caption: "הנר הסגור האחרון" },
    },
    verdict: {
      TRACK: "להוסיף למעקב",
      WAIT: "מגמה תקינה — אין נר איתות",
      NO_TRACK: "לא למעקב",
      INCOMPLETE: "חסר מידע",
    },
    verdictHint: {
      TRACK: "כל שבע הבדיקות עוברות — המנייה נכנסת לרשימת המעקב של החודש והנר האחרון הוא איתות קנייה.",
      WAIT: "הסחירות והמגמה החודשית עוברות, אך הנר הסגור האחרון עדיין אינו נר איתות. לבדוק שוב בחודש הבא.",
      NO_TRACK: "שער הסחירות או המגמה החודשית נכשלו — להשאיר מחוץ לרשימה.",
      INCOMPLETE: "חלק מהבדיקות לא נענו מהנתונים — השלימו אותן ידנית.",
    },
    chart: { title: "גרף", caption: "נרות חודשיים + MA5" },
    chartHint: "גלילה או צביטה לזום · Shift-גלילה או גרירה להזזה · הקשה להצגת הצלב",
    legendMa5: "MA5",
    edited: "נערך",
    confTip: { exact: "נוסחה דטרמיניסטית מהנתונים", swing: "דטרמיניסטי לפי הגדרת התנודה — בדקו את הנקודות", guess: "פרשנות מיטבית — ודאו ויזואלית" },
  },
};
